# Generated by Django 5.1.1 on 2024-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_category_color_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='flair',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
