# Generated by Django 5.1.1 on 2024-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='French', max_length=20),
        ),
        migrations.AddField(
            model_name='bookrental',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
