# Generated by Django 5.1.1 on 2024-11-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0005_book_language_bookrental_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrental',
            name='reserved',
            field=models.BooleanField(default=True),
        ),
    ]
