# Generated by Django 5.1.1 on 2024-11-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0007_book_rating_bookrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrental',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
